/* ════════════════════════════════════════════
   成就图鉴·唯一事实源（借鉴 色色灵感状态栏V3.2：声明式目录 + 稀有度 + 隐藏 + 趣评）
   - 新增/修改成就只改本文件；条目约束见 achievementEngine.AchvDef 注释；
   - id 必须 cat_ 前缀且全局唯一（守卫在 achievementEngine.test.ts）；
   - metric 只准读 AchvCtx（纯函数）；rarity 用 D/C/B/A/S/SS/SSS（RARITY_CLS 有色）；
   - category 对齐 AchievementPanel 筛选片：战斗/探索/任务/生存/其他（hidden 条目落档时自动归「隐藏」）；
   - ⚠ 措辞守项目术语线：五阶前不点破的黑幕不写名（用「帷幕/封存的名字」指代）、不用修仙词。
════════════════════════════════════════════ */
import type { AchvDef } from './achievementEngine';

export const ACHV_CATALOG: readonly AchvDef[] = [
  /* ── 阶位·成长（战斗）── */
  { id: 'cat_tier2', name: '初窥门径', desc: '晋升二阶——从此在轮回乐园里，你不再是最底层的那批新人。', condition: '阶位达到二阶', category: '战斗', type: '阶段', rarity: 'C',
    quip: '乐园的楼梯还长着呢，先别急着回头看。', target: 2, metric: (c) => c.tierNum },
  { id: 'cat_tier4', name: '属性觉醒', desc: '晋升四阶，跨过「属性觉醒」的门槛——真实属性自此对你敞开。', condition: '阶位达到四阶', category: '战斗', type: '阶段', rarity: 'B',
    quip: '从这一步起，数字开始说真话。', target: 4, metric: (c) => c.tierNum },
  { id: 'cat_tier5', name: '帷幕之后', desc: '晋升五阶——有些被封存的名字，从此可以说出口了。', condition: '？？？', category: '战斗', type: '阶段', rarity: 'A', hidden: true,
    quip: '现在，你知道得太多了。', target: 5, metric: (c) => c.tierNum },
  { id: 'cat_tier7', name: '一方强者', desc: '晋升七阶。放在任何一个任务世界，你都是足以改写格局的存在。', condition: '阶位达到七阶', category: '战斗', type: '阶段', rarity: 'S',
    target: 7, metric: (c) => c.tierNum },
  { id: 'cat_tier10', name: '摘星之手', desc: '晋升十阶。同阶的契约者，一只手数得过来。', condition: '阶位达到十阶', category: '战斗', type: '阶段', rarity: 'SS',
    quip: '往上看，人影已经很稀了。', target: 10, metric: (c) => c.tierNum },
  { id: 'cat_tier14', name: '行至彼岸', desc: '晋升十四阶——阶位表的尽头。', condition: '？？？', category: '战斗', type: '阶段', rarity: 'SSS', hidden: true,
    quip: '十四阶之上再无台阶。欢迎来到没有扶手的地方。', target: 14, metric: (c) => c.tierNum },
  { id: 'cat_attr300', name: '血肉重铸', desc: '六维属性总和突破 300，这具身体已远非凡俗。', condition: '六维总和 ≥ 300', category: '战斗', type: '累计', rarity: 'C',
    target: 300, metric: (c) => c.attrTotal },
  { id: 'cat_attr1000', name: '超凡入圣', desc: '六维属性总和突破 1000。你的每一次呼吸都是低阶者的极限爆发。', condition: '六维总和 ≥ 1000', category: '战斗', type: '累计', rarity: 'A',
    target: 1000, metric: (c) => c.attrTotal },
  { id: 'cat_realattr10', name: '真实之力', desc: '真实属性直加值累计 10 点——在判定的世界里，你说的话更接近「规则」。', condition: '真实属性直加 ≥ 10', category: '战斗', type: '累计', rarity: 'S',
    target: 10, metric: (c) => c.realAttrPlus },
  { id: 'cat_kills100', name: '百人斩', desc: '武器上的杀敌记录合计超过 100。', condition: '武器累计杀敌 ≥ 100', category: '战斗', type: '累计', rarity: 'B',
    quip: '武器上的刻痕，比你诚实。', target: 100, metric: (c) => c.weaponKills },
  { id: 'cat_skill20', name: '技多不压身', desc: '习得技能达到 20 个。', condition: '技能数 ≥ 20', category: '战斗', type: '累计', rarity: 'B',
    target: 20, metric: (c) => c.skillCount },
  { id: 'cat_trait10', name: '天赋异禀', desc: '持有天赋达到 10 个。', condition: '天赋数 ≥ 10', category: '战斗', type: '累计', rarity: 'B',
    target: 10, metric: (c) => c.traitCount },

  /* ── 世界·轮回（探索/任务）── */
  { id: 'cat_world1', name: '初临异界', desc: '第一次踏入任务世界。门在身后合拢的那一刻，退路这个词就删掉了。', condition: '踏入 1 个任务世界', category: '探索', type: '阶段', rarity: 'D',
    quip: '门后是什么不重要，重要的是你推开了。', target: 1, metric: (c) => c.worldsVisited },
  { id: 'cat_world5', name: '维度旅人', desc: '踏入过 5 个任务世界。护照上盖满了不存在的国度。', condition: '踏入 5 个任务世界', category: '探索', type: '累计', rarity: 'B',
    target: 5, metric: (c) => c.worldsVisited },
  { id: 'cat_clear1', name: '初次通关', desc: '第一次活着完成任务世界并全身而退。', condition: '通关 1 个任务世界', category: '任务', type: '阶段', rarity: 'B',
    quip: '活着回来，就已经赢了一半人。', target: 1, metric: (c) => c.worldsCleared },
  { id: 'cat_clear3', name: '轮回常客', desc: '通关 3 个任务世界。你开始有了自己的一套生存流程。', condition: '通关 3 个任务世界', category: '任务', type: '累计', rarity: 'A',
    target: 3, metric: (c) => c.worldsCleared },
  { id: 'cat_clear10', name: '无限流老手', desc: '通关 10 个任务世界。', condition: '通关 10 个任务世界', category: '任务', type: '累计', rarity: 'SS',
    quip: '对你来说，世界危机大概只是个周三。', target: 10, metric: (c) => c.worldsCleared },
  { id: 'cat_ratingS', name: '完美评价', desc: '任一任务世界的离世综合评价达到 S 及以上。', condition: '单世界综合评价 ≥ S', category: '任务', type: '特殊', rarity: 'S',
    quip: '评分栏那一行，连主神都挑不出毛病。', target: 7, metric: (c) => c.bestRatingNum },
  { id: 'cat_source100', name: '世界之源·百', desc: '在单个任务世界累计获取 100 点世界之源。', condition: '单世界世界之源 ≥ 100', category: '任务', type: '累计', rarity: 'B',
    target: 100, metric: (c) => c.worldSource },
  { id: 'cat_turn100', name: '百回长途', desc: '累计推进 100 回合。', condition: '累计回合 ≥ 100', category: '生存', type: '累计', rarity: 'C',
    quip: '你在这里度过的时间，够看完一部烂尾长篇了。', target: 100, metric: (c) => c.turnCount },
  { id: 'cat_turn1000', name: '千回长梦', desc: '累计推进 1000 回合。轮回于你，已经是一种生活方式。', condition: '累计回合 ≥ 1000', category: '生存', type: '累计', rarity: 'A',
    target: 1000, metric: (c) => c.turnCount },

  /* ── 资产·收集（其他）── */
  { id: 'cat_coin10k', name: '第一桶金', desc: '乐园币持有量突破 1 万。', condition: '乐园币 ≥ 10000', category: '其他', type: '累计', rarity: 'C',
    quip: '乐园币不会说谎，但商人会。', target: 10000, metric: (c) => c.coins },
  { id: 'cat_coin100k', name: '富甲一方', desc: '乐园币持有量突破 10 万。走进交易区时，掌柜们的腰都弯了三分。', condition: '乐园币 ≥ 100000', category: '其他', type: '累计', rarity: 'A',
    target: 100000, metric: (c) => c.coins },
  { id: 'cat_soul1k', name: '灵魂账簿', desc: '灵魂钱币持有量突破 1000。', condition: '灵魂钱币 ≥ 1000', category: '其他', type: '累计', rarity: 'B',
    quip: '这种钱拿在手里，最好别细想它的来路。', target: 1000, metric: (c) => c.soulCoins },
  { id: 'cat_item50', name: '仓鼠本能', desc: '背包物品达到 50 件（货币不算）。', condition: '背包物品 ≥ 50 件', category: '其他', type: '累计', rarity: 'C',
    quip: '「总有一天用得上」——你每次都这么说。', target: 50, metric: (c) => c.itemCount },
  { id: 'cat_gradeGold', name: '金光入库', desc: '持有金色及以上品级的物品。', condition: '持有 ≥ 金色 品级物品', category: '其他', type: '特殊', rarity: 'A',
    target: 7, metric: (c) => c.bestGradeNum },
  { id: 'cat_gradeLegend', name: '传说之证', desc: '持有传说级及以上品级的物品。它被你拿在手里，而不是躺在传说里。', condition: '持有 ≥ 传说级 品级物品', category: '其他', type: '特殊', rarity: 'S',
    target: 9, metric: (c) => c.bestGradeNum },
  { id: 'cat_gradeOrigin', name: '起源回响', desc: '持有起源及以上品级的物品——万物开端的碎屑，落在了你的背包里。', condition: '？？？', category: '其他', type: '特殊', rarity: 'SSS', hidden: true,
    quip: '有些东西不是你捡到了它，是它选中了你。', target: 13, metric: (c) => c.bestGradeNum },
  { id: 'cat_enh8', name: '精工细作', desc: '任一装备强化至 +8。', condition: '装备强化 ≥ +8', category: '其他', type: '阶段', rarity: 'B',
    target: 8, metric: (c) => c.bestEnhance },
  { id: 'cat_enh16', name: '锻造之巅', desc: '任一装备强化至 +16——强化台的尽头。', condition: '装备强化 ≥ +16', category: '其他', type: '阶段', rarity: 'SS',
    quip: '铁匠看你的眼神已经变了。', target: 16, metric: (c) => c.bestEnhance },
  { id: 'cat_title10', name: '名号响亮', desc: '持有称号达到 10 个。', condition: '称号数 ≥ 10', category: '其他', type: '累计', rarity: 'B',
    quip: '称号再多，名片也就一张脸。', target: 10, metric: (c) => c.titleCount },
  { id: 'cat_subprof3', name: '斜杠契约者', desc: '掌握 3 门副职业。主业保命，副业保生活。', condition: '副职业 ≥ 3 门', category: '其他', type: '累计', rarity: 'A',
    target: 3, metric: (c) => c.subProfCount },
  { id: 'cat_ach20', name: '收藏家', desc: '解锁的成就总数达到 20 条（含叙事与设施授予）。', condition: '成就总数 ≥ 20', category: '其他', type: '累计', rarity: 'B',
    quip: '连成就都要集齐——这病，和仓鼠症是并发的。', target: 20, metric: (c) => c.achievementCount },
  { id: 'cat_repute5', name: '声名显赫', desc: '任一声誉维度在当前世界升至满档。街谈巷议里，你已经是个「人物」。', condition: '任一声誉维度满档', category: '其他', type: '特殊', rarity: 'A',
    target: 5, metric: (c) => c.reputeMax },

  /* ── 众生·羁绊（生存 + 隐藏）── */
  { id: 'cat_npc20', name: '众生相', desc: '名册在档角色达到 20 人。', condition: '在档角色 ≥ 20', category: '生存', type: '累计', rarity: 'C',
    target: 20, metric: (c) => c.npcCount },
  { id: 'cat_npc50', name: '人间观察', desc: '名册在档角色达到 50 人。每个名字背后都是一段没写完的故事。', condition: '在档角色 ≥ 50', category: '生存', type: '累计', rarity: 'B',
    target: 50, metric: (c) => c.npcCount },
  { id: 'cat_trust95', name: '性命相托', desc: '有人对你的信任达到 95——在这种世道里，这比任何装备都稀有。', condition: '任一角色信任 ≥ 95', category: '生存', type: '特殊', rarity: 'A',
    quip: '这种东西弄丢一次，就再也捡不回来了。', target: 95, metric: (c) => c.trustMax },
  { id: 'cat_corr60', name: '沦陷', desc: '有人为你一步步弃守了自己的原则。', condition: '？？？', category: '生存', type: '特殊', rarity: 'A', hidden: true,
    quip: '原则这东西，第一次弯下来以后，就软了。', target: 60, metric: (c) => c.corruptionMax },
  { id: 'cat_corr95', name: '万劫不复', desc: '有人为你沉沦至深，再也回不到从前的自己。', condition: '？？？', category: '生存', type: '特殊', rarity: 'S', hidden: true,
    target: 95, metric: (c) => c.corruptionMax },
  { id: 'cat_dead10', name: '生死看惯', desc: '名册上累计有 10 个名字被划去。', condition: '在档死亡角色 ≥ 10', category: '生存', type: '累计', rarity: 'B',
    quip: '名册越来越薄，你翻页的手越来越稳。', target: 10, metric: (c) => c.npcDead },

  /* ── 🔗 调教·私养（生存 + 隐藏）── */
  { id: 'cat_train_first', name: '初执教鞭', desc: '第一次把一个人纳入调教、并让她的调教值真正开始累积。', condition: '？？？', category: '生存', type: '阶段', rarity: 'C', hidden: true,
    quip: '规矩这东西，立起来容易，守下去难——对她，也对你。', target: 1, metric: (c) => c.trainMax },
  { id: 'cat_train60', name: '循循善诱', desc: '有人的调教值累积到 60——她开始习惯你定的节奏了。', condition: '？？？', category: '生存', type: '特殊', rarity: 'A', hidden: true,
    target: 60, metric: (c) => c.trainMax },
  { id: 'cat_train95', name: '调教大成', desc: '有人被你调教至臻境，一个眼神她就懂。', condition: '？？？', category: '生存', type: '特殊', rarity: 'S', hidden: true,
    quip: '到这一步，命令都省了。', target: 95, metric: (c) => c.trainMax },
  { id: 'cat_dev100', name: '开发殆尽', desc: '有人的某一处被你开发到了极限。', condition: '？？？', category: '生存', type: '特殊', rarity: 'A', hidden: true,
    target: 100, metric: (c) => c.devMax },
  { id: 'cat_pregnant', name: '血脉延续', desc: '有人为你孕育了新的生命。', condition: '？？？', category: '生存', type: '特殊', rarity: 'A', hidden: true,
    quip: '有些牵绊，从此再也解不开了。', target: 1, metric: (c) => c.pregnantCount },
  { id: 'cat_harem5', name: '调教成宫', desc: '同时纳入调教的对象达到 5 人——你的私养名册，已经排得下一屋子。', condition: '？？？', category: '生存', type: '累计', rarity: 'B', hidden: true,
    quip: '雨露均沾这四个字，说起来轻巧。', target: 5, metric: (c) => c.trainRosterCount },
  { id: 'cat_orgasm100', name: '百炼成欢', desc: '让同一个人在你手上累计高潮 100 次。', condition: '？？？', category: '生存', type: '特殊', rarity: 'A', hidden: true,
    quip: '她的身体比她的嘴，诚实太多了。', target: 100, metric: (c) => c.orgasmMax },
  { id: 'cat_orgasm500', name: '极乐千帆', desc: '让同一个人在你手上累计高潮 500 次——她的身体早已把你刻进了本能。', condition: '？？？', category: '生存', type: '特殊', rarity: 'S', hidden: true,
    target: 500, metric: (c) => c.orgasmMax },
  { id: 'cat_creampie50', name: '灌注成瘾', desc: '在同一个人体内累计内射 50 次。', condition: '？？？', category: '生存', type: '特殊', rarity: 'A', hidden: true,
    target: 50, metric: (c) => c.creampieMax },
  { id: 'cat_birth', name: '开枝散叶', desc: '有人为你诞下了孩子——不再只是孕育，而是真的降生了。', condition: '？？？', category: '生存', type: '特殊', rarity: 'A', hidden: true,
    quip: '从此这世上，多了一个流着你血的人。', target: 1, metric: (c) => c.birthMax },

  /* ── 设施·基业（探索/其他）── */
  { id: 'cat_abyss10', name: '幽冥初探', desc: '在幽冥回廊下探至第 10 层。', condition: '回廊最深 ≥ 10 层', category: '探索', type: '阶段', rarity: 'B',
    target: 10, metric: (c) => c.abyssDeepest },
  { id: 'cat_abyss50', name: '深不见底', desc: '在幽冥回廊下探至第 50 层。越往下，越安静。', condition: '回廊最深 ≥ 50 层', category: '探索', type: '阶段', rarity: 'S',
    quip: '下面没有灯。你自己就是灯。', target: 50, metric: (c) => c.abyssDeepest },
  { id: 'cat_teamFound', name: '立旗结社', desc: '创立属于自己的冒险团。从此你的名字前面多了一个团徽。', condition: '创立冒险团', category: '其他', type: '阶段', rarity: 'C',
    target: 1, metric: (c) => c.teamFounded },
  { id: 'cat_teamS', name: '传奇之团', desc: '冒险团评级达到 S 级。乐园布告栏上，你们的委托回执被贴在最上排。', condition: '冒险团评级 ≥ S', category: '其他', type: '阶段', rarity: 'S',
    target: 6, metric: (c) => c.teamRankNum },
  { id: 'cat_terr3', name: '一方基业', desc: '个人基地建设至 3 级。', condition: '基地等级 ≥ 3', category: '其他', type: '阶段', rarity: 'B',
    target: 3, metric: (c) => c.territoryLevel },
  { id: 'cat_terr5', name: '王土', desc: '个人基地建设至 5 级——这片地方，已经配得上「领地」二字。', condition: '基地等级 ≥ 5', category: '其他', type: '阶段', rarity: 'S',
    target: 5, metric: (c) => c.territoryLevel },
];
